### ISSUE TITLE
Date errors using filter

### ISSUE THREAD

**Issue by LedgerLand** [officecenter/Autotask#15] opened 2019-03-25 21:30 UTC
When querying tickets using the filter I am getting issues with the date.  The command being used is:

$Tickets = Get-AtwsTicket -Filter {accountid -eq $ataccountid -and issuetype -eq 18 -and createdate -ge $startdate -and createdate -le $EndDate}

When running it outputs the following error:

```
VERBOSE: Get-AtwsTicket: Begin of function
VERBOSE: Get-AtwsTicket: Passing -Filter raw to Get function
VERBOSE: Get-AtwsData: Mashing parameters into an array of strings.
VERBOSE: Get-AtwsData: Checking query for variables that have survived as string
VERBOSE: Get-AtwsData: Substituting $ataccountid for its value
VERBOSE: Get-AtwsData: Converting query string into QueryXml. String as array looks like: Ticket, accountid, -eq, 29781522, -and, issuetype, -eq, 18, -and, cr
eatedate, -ge, $startdate, -and, createdate, -le, $EndDate
VERBOSE: Get-AtwsData: QueryXml looks like: <queryxml><entity>Ticket</entity><query><field>accountid<expression op="Equals">29781522</expression></field><cond
ition operator="and"><field>issuetype<expression op="Equals">18</expression></field></condition><condition operator="and"><field>createdate<expression op="Gre
aterThanorEquals">$startdate</expression></field></condition><condition operator="and"><field>createdate<expression op="LessThanOrEquals">$EndDate</expression
></field></condition></query></queryxml>
VERBOSE: Get-AtwsData: Adding looping construct to query to handle more than 500 results.
VERBOSE: Get-AtwsData: Passing QueryXML to Autotask API
Get-AtwsData : Conversion failed when converting date and/or time from character string.
At line:66334 char:15
+ ...   $Result = Get-AtwsData -Entity $EntityName -Filter $Filter -Connect ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
 
VERBOSE: Get-AtwsData: End of function
VERBOSE: Get-AtwsTicket: Number of entities returned by base query: 0
VERBOSE: Get-AtwsTicket: End of function
```

**Comment by klemmestad** [comment] 2019-03-26 07:23
Publishing an updated module version as I write this. There is a bugfix there that may possibly fix this for you. Could you try it out?

**Comment by LedgerLand** [comment] 2019-03-26 08:47
Just downloaded the latest version but I'm still getting the same message:

Get-AtwsTicket: Begin of function
Get-AtwsTicket: Passing -Filter raw to Get function
Get-AtwsData: Mashing parameters into an array of strings.
Get-AtwsData: Checking query for variables that have survived as string
Get-AtwsData: Substituting $ataccountid for its value
Get-AtwsData: Converting query string into QueryXml. String as array looks like: Ticket, accountid, -eq, 29781522, -and, issuetype, -eq, 18, -and, createdate, -ge, $startdate, -and, 
createdate, -le, $EndDate
Get-AtwsData: QueryXml looks like: <queryxml><entity>Ticket</entity><query><field>accountid<expression op="Equals">29781522</expression></field><condition 
operator="and"><field>issuetype<expression op="Equals">18</expression></field></condition><condition operator="and"><field>createdate<expression 
op="GreaterThanorEquals">$startdate</expression></field></condition><condition operator="and"><field>createdate<expression 
op="LessThanOrEquals">$EndDate</expression></field></condition></query></queryxml>
Get-AtwsData: Adding looping construct to query to handle more than 500 results.
Get-AtwsData: Passing QueryXML to Autotask API
Get-AtwsData : Conversion failed when converting date and/or time from character string.
At line:66334 char:15
+ ...   $Result = Get-AtwsData -Entity $EntityName -Filter $Filter -Connect ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
 
Get-AtwsData: End of function
Get-AtwsTicket: Number of entities returned by base query: 0
Get-AtwsTicket: End of function

**Comment by LedgerLand** [comment] 2019-03-26 09:07
Ok so slightly different error. I removed all local caches of the Autotask module and exited the powershell ISE and restarted. Now when I run it I get the following error:

Get-AtwsTicket: Begin of function
Get-AtwsTicket: Passing -Filter raw to Get function
Get-AtwsData: Mashing parameters into an array of strings.
Get-AtwsData: Checking query for variables that have survived as string
Get-AtwsData: Substituting $ataccountid for its value
Get-AtwsData: Substituting $startdate for its value
You cannot call a method on a null-valued expression.
At C:\Users\RobFranklin\Documents\WindowsPowerShell\Modules\Autotask\1.6.1.6\Private\Get-AtwsData.ps1:164 char:15
+           If ($Value.GetType().Name -eq 'DateTime')
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Get-AtwsData: Substituting $EndDate for its value
You cannot call a method on a null-valued expression.
At C:\Users\RobFranklin\Documents\WindowsPowerShell\Modules\Autotask\1.6.1.6\Private\Get-AtwsData.ps1:164 char:15
+           If ($Value.GetType().Name -eq 'DateTime')
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Get-AtwsData: Converting query string into QueryXml. String as array looks like: Ticket, accountid, -eq, 29781522, -and, issuetype, -eq, 18, -and, createdate, -ge, -and, createdate, -le
Get-AtwsData: QueryXml looks like: <queryxml><entity>Ticket</entity><query><field>accountid<expression op="Equals">29781522</expression></field><condition 
operator="and"><field>issuetype<expression op="Equals">18</expression></field></condition><condition operator="and"><field>createdate<expression 
op="GreaterThanorEquals">-and</expression></field></condition><field>createdate<expression op="LessThanOrEquals"></expression></field></query></queryxml>
Get-AtwsData: Adding looping construct to query to handle more than 500 results.
Get-AtwsData: Passing QueryXML to Autotask API
Get-AtwsData : Conversion failed when converting date and/or time from character string.
At C:\Users\RobFranklin\Documents\WindowsPowershell\Cache\7661\Dynamic\Get-Ticket.ps1:939 char:15
+     $Result = Get-AtwsData -Entity $EntityName -Filter $Filter
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
 
Get-AtwsData: End of function
Get-AtwsTicket: Number of entities returned by base query: 0
Get-AtwsTicket: End of function

On checking the variables $StartDate and $EndDate they both have data in them and they have a datatype of string.....this is REALLY odd?

**Comment by klemmestad** [comment] 2019-03-26 10:23
Oh! Your variables has the same name as the parameters they belong to. I am checking for, and receiving data for the parameters, not your version. Try to give your variables different names to confirm: Call them $xCreateDate and $xEndDate or something like that just for test. I may have to rewrite the testing of scopes for this to be fixed...

**Comment by LedgerLand** [comment] 2019-03-26 11:04
I did think this may be an issue so I changed the names to $StartOfMonth and $EndOfMonth but that still threw the same error.

**Comment by LedgerLand** [comment] 2019-03-26 14:39
Not sure if it's connected or not but the "Intellisense" for parameters such as "QueueID" no longer works. Also, when I run one the scripts that worked previous to create tickets I get errors and they fail to create. When I list installed modules I get this.

`ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Script     1.6.1.6    Autotask                            {Connect-AtwsWebAPI, Get-AtwsAccount, Get-AtwsAccountAlert, Get-AtwsAccountLocation...}               `

**Comment by klemmestad** [comment] 2019-03-26 15:37
Another bug, but fortunately it is easy to work around: Re-load the module with -Force (if you connect with -ArgumentList) or re-run Connect-AtwsWebApi.

**Comment by LedgerLand** [comment] 2019-03-26 17:28
Tried that but still getting the same with no intellisense? Also tried uninstalling and installing the module as well as a reboot.....it's all getting very strange!

**Comment by klemmestad** [comment] 2019-03-27 08:30
Bugfixes are in the pipeline, but could you try

`Import-Module 'Autotask' -Force -ArgumentList $Credentials, $ApiTrackingid, '*'`

This should re-import the module and refresh any functions with picklists

**Comment by klemmestad** [comment] 2019-03-27 08:33
Doing the same with Connect-AtwsWebAPI (Connect-AutotaskWebApi is an alias for this function):

`Connect-AtwsWebAPI -Credential $Credentials -ApiTrackingIdentifier $ApiTrackingid -RefreshCache `

**Comment by klemmestad** [comment] 2019-03-27 12:23
New version 1.6.1.8 is out with a fix for this problem.

**Comment by LedgerLand** [comment] 2019-03-27 12:48
Just downloaded the latest update and Intellisense is working now :-)

I'm still getting the same issue with passing the date through:

`$Tickets = Get-AtwsTicket -Filter {accountid -eq $ataccountid -and issuetype -eq 18 -and createdate -ge $StartOfMonth -and createdate -le $EndOfMonth} -Verbose
`
Gives the following:

```
Get-AtwsData : Get-AtwsData: Could not find any variable called $StartOfMonth. Is it misspelled or has it not been set yet?
At C:\Users\RobFranklin\Documents\WindowsPowershell\Cache\7661\Dynamic\Get-AtwsTicket.ps1:1153 char:15
+     $Result = Get-AtwsData -Entity $EntityName -Filter $Filter
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
 
Get-AtwsTicket: Number of entities returned by base query: 0

```

When I check the variable I get the following:

```
IsPublic IsSerial Name                                     BaseType                                                                                                                           
-------- -------- ----                                     --------                                                                                                                           
True     True     String                                   System.Object                                                                                                                      
```

Strange thing is I only get this error when using the "-filter" all other commands work fine!

**Comment by klemmestad** [comment] 2019-03-27 12:58
Great! Then lets try to figure this problem out. Could you post the code you use to generate $StartOfMonth and $EndOfMonth? And what are your regional settings in Windows? I'll try to repeat the error on my own system with the same settings as you.

**Comment by LedgerLand** [comment] 2019-03-27 13:19
Ok, these are the functions that generate the start and end day

```
function Get-StartOfMonth{
    Param
    (
    [Parameter(mandatory=$true)]
    [string] $date
    )
    $startofmonth = Get-Date $date -day 1 -hour 0 -minute 0 -second 0

    return $startofmonth
}

function Get-EndOfMonth{
    Param
    (
    [Parameter(mandatory=$true)]
    [string] $date
    )
    $startofmonth = Get-Date $date -day 1 -hour 0 -minute 0 -second 0
    $endofmonth = (($startofmonth).AddMonths(1).AddSeconds(-1))

    return $endofmonth

}


```

This is where it is called prior to running "Get-AtWsTicket", $RepDate is where the function is fed a date or it defaults to today:

```
    if (!$RepDate)
    {
        $SearchDate = Get-Date -Format "dd/MM/yyyy hh:mm:ss"
    }
    else
    {
        $SearchDate = $RepDate
    }

    $StartDate = Get-StartOfMonth -date $SearchDate.ToString()
    $EndDate = Get-EndOfMonth -date $SearchDate.ToString()

    $StartOfMonth = get-date $StartDate -Format "MM/dd/yyyy"
    $EndOfMonth = get-date $enddate -Format "MM/dd/yyyy"
```

Regional settings on my PC are all set to United Kingdom

I have tried with the date in US and UK format but get the same result

Thanks for all your help, really really appreciate it!!

**Comment by klemmestad** [comment] 2019-03-27 13:32
I will test that because it should have worked, but it would be better if you dropped the use of `-Format` and `.ToString()`. Just pass your variables as DateTime objects to any function and the module will handle timezone conversion and can make sure dates and datetime is formatted the way the API expects. When you pass your dates as string (and you do if you use `-Format`) it will mostly work, but then you will have to handle the time difference between your local time and the API (the API only talks Eastern Standard Time - annoyingly enough...)

**Comment by LedgerLand** [comment] 2019-03-27 14:23
Understood, just updated the code to the following and still getting the same error:

```
if (!$RepDate)
    {
        $SearchDate = Get-Date -Format "dd/MM/yyyy hh:mm:ss"
    }
    else
    {
        $SearchDate = $RepDate
    }

    $StartOfMonth = Get-StartOfMonth -date $SearchDate
    $EndOfMonth = Get-EndOfMonth -date $SearchDate

$Tickets = Get-AtwsTicket -Filter {accountid -eq $ataccountid -and issuetype -eq 18 -and createdate -ge $StartOfMonth -and createdate -le $EndOfMonth} -Verbose
```

Still get the same error:

```
Get-AtwsData : Get-AtwsData: Could not find any variable called $StartOfMonth. Is it misspelled or has it not been set yet?
At C:\Users\User\Documents\WindowsPowershell\Cache\7661\Dynamic\Get-AtwsTicket.ps1:1153 char:15
+     $Result = Get-AtwsData -Entity $EntityName -Filter $Filter
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
 
Get-AtwsTicket: Number of entities returned by base query: 0
```

```
$StartOfMonth.GetType()

IsPublic IsSerial Name                                     BaseType                                                                                                                           
-------- -------- ----                                     --------                                                                                                                           
True     True     DateTime                                 System.ValueType    
```

**Comment by klemmestad** [comment] 2019-03-27 14:56
Okay, I think I have figured it out. PowerShell and variable scopes are useful, but in this particular case it causes a problem. For a variable to be accessible by the core helper functions they have to be set i a scope that is available to other functions. Variables inside functions are local by design. Can you try to explicitly set them to the script scope and try again? I.e.:

`$Script:StartOfMonth = Get-StartOfMonth -date $SearchDate`
`$Script:EndOfMonth = Get-EndOfMonth -date $SearchDate`

**Comment by LedgerLand** [comment] 2019-03-27 15:22
That makes sense, I've updated the code and it's still throwing the same error.....this is really strange!:

```
$Script:StartOfMonth = Get-StartOfMonth -date $SearchDate
$Script:EndOfMonth = Get-EndOfMonth -date $SearchDate

$Tickets = Get-AtwsTicket -Filter {accountid -eq $ataccountid -and issuetype -eq 18 -and createdate -ge $Script:StartOfMonth -and createdate -le $Script:EndOfMonth} -Verbose
Get-AtwsData : Get-AtwsData: Could not find any variable called $StartOfMonth. Is it misspelled or has it not been set yet?
At C:\Users\User\Documents\WindowsPowershell\Cache\7661\Dynamic\Get-AtwsTicket.ps1:1153 char:15
+     $Result = Get-AtwsData -Entity $EntityName -Filter $Filter
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
 
Get-AtwsTicket: Number of entities returned by base query: 0
```

**Comment by klemmestad** [comment] 2019-03-27 20:44
Okay, this means I will have to rethink the variable expansion code. It works for interactive scripting, but not when creating functions that call functions, obviously. But you need to get some work done. My suggestion is to do the opposite of what I just recommended: Format your dates as strings, do the variable expansion in your own code before passing the filter to the function. Example:

```posh
$Filter = "accountid -eq $ataccountid -and createdate -ge $StartofMonth -and createdate -le $EndOfMonth"
$Tickets = Get-AtwsTicket -Filter $Filter
```

NOTE: According to the API documentation you should always use sortable date format for datetime (`Get-Date -Format s`) and for dates you should always use format yyyy-mm-dd in queries. If you want things to be entirely precise you should add timezone offset to the datetime string. If you make a query for all tickets created betweeen 20190301T00:00:00 and 20190331T23:59:59 then you will get all tickets created between 20190301T04:00:00 and 20190401T03:59:59 UK time, give or take daylights savings time (in the US). 

I use this code to get it right (variable $Datetime is supplied by you):

```posh
      # Use local time for DateTime
      $OffsetSpan = (Get-TimeZone).BaseUtcOffset
      
      # Create the correct text string                           
      $Offset = '{0:00}:{1:00}' -F $OffsetSpan.Hours, $OffsetSpan.Minutes
      If ($OffsetSpan.Hours -ge 0) {
        $Offset = '+{0}' -F $Offset
      }
      $Value = '{0}{1}' -F $(Get-Date $DateTime -Format s), $Offset
```

Hope that helps!

**Comment by JsonWud** [comment] 2019-03-27 21:32
@ledgerland have you tried your query using datetime objects instead of strings?

When I'm testing queries at the command line I usually give any parameters that are looking for a date something like the following because Autotask doesn't consider the time portion for most of the queries I make (contractserviceunit).

[datetime]'3/27/2019'

**Comment by LedgerLand** [comment] 2019-04-04 10:17
Sorry for not getting back sooner @klemmestad, doing it that way worked perfectly and I've not got it filtering the way I needed it. For me, I wouldn't worry to much about trying to resolve it as I have a fix now and it's not too much of an effort work around it.

For anyone else with this problem, the way to resolve it was as follows:

```
    $Filter = "accountid -eq $ataccountid -and createdate -ge $Script:StartOfMonth -and createdate -le $Script:EndOfMonth"
    $Tickets = Get-AtwsTicket -Filter $Filter

```
Doing it this way the parameters pass correctly.

Thanks again for all your help, you sir are a legend!!

**Closed** 2019-05-22 14:05 UTC
